### PR TITLE
Clarified GPU description. 

### PR DESCRIPTION
**Pull request by ronatartifact**
Added link to design docs for creating new GPU type.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
Ron, your PR looks fine. It is kind of convention to have a ticket describing what needs to be done and then prepend the ticket id to the PR description. On the other hand we are moving to github with tickets as well (slowly) and in that case it doesn't make sense to have a jira ticket as well.

this LGTM
@runseb Do we apply the 2 lgtm on docs as well?

**Comment by terbolous** [comment]
LGTM, verified in the github preview that the output renders correctly.

**Comment by pdion891** [comment]
LGTM, formating is fine in the current sphinx theme. 

Having the link to the feature spec mention at line 305 would have been a nice to have. 

Thanks for the PR!

**Comment by ronatartifact** [comment]
I considered using a link but was unsure about the policy of references 
to outside documents.

It creates a link that can be easily broken by the developers if they 
change the structure or location of the design docs without thinking 
that the official Docs have links.

That is why I used the title of the page and the reference by name to 
the 4.4 design docs.

If the information is relatively stable and worth knowing, perhaps a 
summary of the Administration implications could be included in a 
section in the Admin docs to eliminate the need for a link to an 
external source.

I am a bit too new and do not use the GPU (as near as I can tell at this 
point) to know where it should be included in the Admin docs and how 
much an Admin (as opposed to a developer) needs to know to add a GPU.

Ron


On 03/11/2015 7:28 AM, Pierrre-Luc Dion wrote:
>
> LGTM, formating is fine in the current sphinx theme.
>
> Having the link to the feature spec mention at line 305 would have 
> been a nice to have.
>
> Thanks for the PR!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/apache/cloudstack-docs-admin/pull/31#issuecomment-153337733>.
>


-- 
Ron Wheeler
President
Artifact Software Inc
email: rwheeler@artifact-software.com
skype: ronaldmwheeler
phone: 866-970-2435, ext 102

**Pull request merged**
