### PR TITLE
CLOUDSTACK-9299: doc for out-of-band management

### PR DESCRIPTION
**Pull request by rhtyd**
Admin documentation for out-of-band management feature

cc @pdion891 @swill

### CODE REVIEW

**Comment by abhinandanprateek** [comment]
read the document LGTM.

**Comment by rhtyd** [comment]
Thanks Abhi, since the feature PR is merged. I'm merging the doc PR as well.

**Comment by swill** [comment]
Thanks for taking care of this @rhtyd.  👍

**Comment by borisstoyanov** [comment]
LGTM, it's already merged anyway. 
👍

**Pull request merged**
