### PR TITLE
More docs on Private Gateway requirements, tagging,etc

### PR DESCRIPTION
**Pull request by andrijapanic**

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@andrijapanic I think it is better to squash into a single commit

**Comment by andrijapanic** [comment]
If you don't mind doing that instead of me, since I'm not a GIT guy, I would really appreciate it :)

**Comment by rafaelweingartner** [comment]
I would not have time right now, but it is always good to learn something new ;)
It is quite easy: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

In a nutshell, you can run: 
`git rebase -i HEAD~<numberOfCommitsYouWantToSquash>`

e.g.: `git rebase -i HEAD~3`

**Comment by andrijapanic** [comment]
Risking to look stupid, but I actually use github website, not very good with git, but will try tomorrow from console :)

**Comment by rafaelweingartner** [comment]
Aha, no problem. It happens.  I actually do not know how to do this via UI.

I could do the squash, but I think it is good to provide you with the opportunity to learn as it is quite useful sometimes.

**Comment by andrijapanic** [comment]
I squashed last 5 commits into single one, forced push to my own fork of repo (seems OK) and now you can check pls.. I could not create NEW PR, (I assume since all changes are identical to files, just no in 1 commit vs 5 commits ???) so it just redirect me to this page here, existing PR 43...

Sorry, a noob here :)

**Comment by rafaelweingartner** [comment]
Everything is in order now. Thanks for the effort!

**Comment by andrijapanic** [comment]
Now, I'm pro 🤣  thx for the help and the learning 👍

**Pull request merged**
