### PR TITLE
CLOUDSTACK-8562: add information on dynamic roles

### PR DESCRIPTION
**Pull request by rhtyd**
Adds documentation on dynamic roles feature

/cc @swill @pdion891

### CODE REVIEW

**Comment by pdion891** [comment]
LGTM,  but we will also have to add part of this addition into the release note of 4.9.

Thanks @bhaisaab

**Comment by bhaisaab** [comment]
Thanks @pdion891 sure after the freeze date, we can add to the release notes list of new APIs, list of new features along with any major changes etc.

**Comment by rhtyd** [comment]
@pdion891 let's merge this now that the feature PR has been accepted

**Comment by borisstoyanov** [comment]
LGMT!

**Comment by rhtyd** [comment]
Thanks @borisstoyanov merging this now.

**Pull request merged**
