### PR TITLE
Adding some french images

### PR DESCRIPTION
**Pull request by lmrv**
I had some french images.
Those images are named *.fr.png.

### CODE REVIEW

**Comment by pdion891** [comment]
nice ! now we need to figure out how to show those images in the french version because the French build still use the orignal images as links.

**Comment by lmrv** [comment]
Hi @pdion891. Are you sure ?
The default behaviour is to use the image with .fr. suffix if available.
I have tested this on my local build and it worked.

**Comment by rafaelweingartner** [comment]
@lmrv thanks!
How is your position here @pdion891?

**Comment by lmrv** [comment]
Hi Rafael,
6 months to get a "changes approved" to a merge request... 
Sorry but I think you should optimize the review process of the doc if you want some contributor to help and contribute.

**Comment by rafaelweingartner** [comment]
Well… what can I tell you? That is how open source software work. It is pretty hard to ask for people to do something when they are doing things mostly for free. Our docs and website repository are a bit slower indeed. I am sorry if that did not fulfill your expectations.

**Comment by nvazquez** [comment]
LGTM

@lmrv sorry for the inconvenience. I would suggest you to push for reviews if you have no input/interactions on your pull requests. You could also make use of the dev mailing list to ask for reviews.

**Comment by rafaelweingartner** [comment]
@nvazquez thanks for the help here!

**Pull request merged**
