### PR TITLE
fix storage section typo

### PR DESCRIPTION
**Pull request by giraffeforestg**
fix storage section typo.

### CODE REVIEW

**Comment by runseb** [comment]
@terbolous can you take care of this ?

**Comment by giraffeforestg** [comment]
Hi

If a new line is not, layout is broken.
Please look at the following.

https://github.com/apache/cloudstack-docs-admin/blob/master/source/storage.rst
Working With Volumes
Note

**Comment by runseb** [comment]
Ok I just applied it on master. Should it go to other branches as well ?

**Comment by giraffeforestg** [comment]
No , it is only here.
Thank you.

**Comment by runseb** [comment]
ok can you close the pull request ? thanks for the patch, keep them coming :)

**Pull request closed without merging**
