### PR TITLE
French Translation of Public_ips_and_vlans_for_account

### PR DESCRIPTION
**Pull request by lmrv**

### CODE REVIEW

**Comment by pdion891** [comment]
LGTM, 

Antoine, I'll merge this PR. Thanks again for the hard work !

**Comment by lmrv** [comment]
Thanks Pierre Luc.
Other PR will come quickly ^^.

We can work on RTD too if you have some times this week.

**Comment by pdion891** [comment]
Antoine, 

I've just merge your PR #42, since then there is a conflict with bin files (.mo) would it be possible to rebase and send an updated version of them ?

Let me know, otherwise I'll find a way...

**Comment by lmrv** [comment]
Hi PL,
Not sure what I done is good.
I rebase my master upon the cloudstack one.
I created a new feature on my fork based on master.
I resolved conflicted files on this feature, then push it to the frenchtranslation one on github.
So now, you should have files that can be merged...

Am I correct ?

**Comment by lmrv** [comment]
PL,
If this won't work, we can close this dirty PR.
Then I will create a new feature base on master and applying my change on it.
This could be a better solution.

What do you think about it ?

**Pull request merged**
