### PR TITLE
index.po and ui.po translated in FR

### PR DESCRIPTION
**Pull request by lmrv**
I started working on a french translation of the admin doc.

### CODE REVIEW

**Comment by karuturi** [comment]
@milamber can you take a look at this please?

**Comment by lmrv** [comment]
Hi Rajani, hi Milamber

My name is Antoine, I come from France.
I actually work on a CloudStack plateform.

I really miss a french translation of the admin doc, so I started to 
translate it.

I first discuss about it with Pierre-Luc Dion.

I have setup my dev environnement, get Transifex trad, and forked the 
project on github (https://github.com/lmrv/cloudstack-docs-admin/).

What I have notice :

- Pot files from Transifex are outdated with the github version of .rst.
- Master branch point to version 4.8 of the doc, not the 4.9.

I am motivated to work on french translation (enougth to write a mail in 
english ^^).
What do you think about it ? Do I have to continue ? Do I have to make 
pull request or only working on my own fork ?

Waiting for your instructions.

Regards

Antoine.

**Comment by pdion891** [comment]
I'll review this PR, give me few days...

**Comment by pdion891** [comment]
@lmrv This is a great start! 

I'm willing to merge this PR, but it's a work in progress so it will not be visible on the main site until the translation is mostly completed.

At least the frame work is in place which is very great! 

Thanks a lot.  It's going to be awesome to have the full translation.

**Comment by pdion891** [comment]
@lmrv if you have a chance to update all files copyright header, to must have the apache2 v2 license header.

Thanks

**Comment by pdion891** [comment]
Hi @lmrv, I've look at your test site, those the page https://cloudstack.le-morvan.com/4.8/service_offerings.html  translation is completed? because I see it half in english.

Thanks again for that huge work !

**Comment by lmrv** [comment]
I did it for you this morning !
22% of de doc is now translated.

I need to read it a second time in order to correct some spelling and conjugation mistakes.

**Comment by pdion891** [comment]
@lmrv I think you are now at 50% completed, right ?  could it be possible to update this PR so we cloud merge this first step ?

Continue the Good work !!

**Comment by lmrv** [comment]
See #41 for the rebase pull request.
I have now reach 50% of translated strings.

**Pull request closed without merging**
